export const worksData = [
    {
        id: 1,
        title: "Vivanta Apartment",
        completion_Data: "2023",
        project_location: "Jaipur, Rajasthan",
        project_type: "New Build",
        project_desc: [
            "A modern, straight-lined apartment crafted for a family of three.",
            "Designed to balance functionality with calm, restorative spaces.",
            "Sleek finishes and concealed storage create a light, clutter-free home.",
            "Executed through detailed planning and streamlined project management.",
        ],
        HeroImg: "/Images/projects/vivanta/heroImg.webp",
        images: [
            { type: "portrait", img: "/Images/projects/vivanta/img_4.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_6.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_22.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_2.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_11.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_7.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_5.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_12.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_13.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_3.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_14.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_18.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_8.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_10.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_22.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_23.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_13.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_20.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_27.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_25.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_15.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_16.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_28.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_29.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_17.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_19.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_30.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_31.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_21.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_24.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_32.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_33.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_26.webp" },
            { type: "portrait", img: "/Images/projects/vivanta/img_34.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_35.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_36.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_37.webp" },
            { type: "landscape", img: "/Images/projects/vivanta/img_38.webp" },
        ],
        tags: [
            "Modern Minimalism",
            "Functional Design",
            "Concealed Storage",
            "Warm Interiors",
            "Project Management",
            "Timeless Aesthetic"
        ],
    },
    {
        id: 2,
        title: "RIDANKO Office",
        completion_Data: "2023",
        project_location: "Jaipur, Rajasthan",
        project_type: "New Build",
        project_desc: [
            "A compact marketing office designed for flexibility and efficiency.",
            "Central zone transforms from meeting space to creative studio setup.",
            "Muted modern palette provides a professional yet adaptable backdrop.",
            "Smart storage and precise planning ensured clutter-free functionality.",
        ],
        HeroImg: "/Images/projects/ridanko/heroImg.webp",
        images: [
            { type: "landscape", img: "/Images/projects/ridanko/img_1.webp" },
            { type: "landscape", img: "/Images/projects/ridanko/img_5.webp" },
            { type: "portrait", img: "/Images/projects/ridanko/img_4.webp" },
            { type: "portrait", img: "/Images/projects/ridanko/img_6.webp" },
            { type: "landscape", img: "/Images/projects/ridanko/img_6.webp" },
            { type: "portrait", img: "/Images/projects/ridanko/img_3.webp" },
            { type: "portrait", img: "/Images/projects/ridanko/img_7.webp" },
            { type: "landscape", img: "/Images/projects/ridanko/img_8.webp" },
        ],
        tags: [
            "Flexible Workspace",
            "Compact Design",
            "Adaptive Interiors",
            "Modern Palette",
            "Creative Studio",
            "Smart Storage"
        ],
    },
    {
        id: 3,
        title: "2 Bedroom Renovation",
        completion_Data: "2023",
        project_location: "Jaipur, Rajasthan",
        project_type: "New Build",
        project_desc: [
            "Two sleek bedrooms designed to feel restful, modern, and clutter-free.",
            "Feature wall panelling adds depth while maintaining an airy ambiance.",
            "Integrated wardrobes maximize storage without visual heaviness.",
            "Efficient coordination ensured every detail met the client’s vision.",
        ],
        HeroImg: "/Images/projects/2bedroom/heroImg.webp",
        images: [
            { type: "landscape", img: "/Images/projects/2bedroom/img_18.webp" },
            { type: "portrait", img: "/Images/projects/2bedroom/img_4.webp" },
            { type: "portrait", img: "/Images/projects/2bedroom/img_6.webp" },
            { type: "landscape", img: "/Images/projects/2bedroom/img_1.webp" },
            { type: "landscape", img: "/Images/projects/2bedroom/img_3.webp" },
            { type: "portrait", img: "/Images/projects/2bedroom/img_5.webp" },
            { type: "portrait", img: "/Images/projects/2bedroom/img_8.webp" },
            { type: "landscape", img: "/Images/projects/2bedroom/img_7.webp" },
            { type: "landscape", img: "/Images/projects/2bedroom/img_10.webp" },
            { type: "portrait", img: "/Images/projects/2bedroom/img_9.webp" },
            { type: "portrait", img: "/Images/projects/2bedroom/img_11.webp" },
            { type: "landscape", img: "/Images/projects/2bedroom/img_13.webp" },
            { type: "landscape", img: "/Images/projects/2bedroom/img_14.webp" },
            { type: "portrait", img: "/Images/projects/2bedroom/img_12.webp" },
            { type: "portrait", img: "/Images/projects/2bedroom/img_16.webp" },
            { type: "landscape", img: "/Images/projects/2bedroom/img_15.webp" },
            { type: "landscape", img: "/Images/projects/2bedroom/img_17.webp" },
        ],
        tags: [
            "Bedroom Design",
            "Sleek Interiors",
            "Modern Detailing",
            "Integrated Storage",
            "Minimal Aesthetic",
            "Functional Elegance"
        ],
    },
    {
        id: 4,
        title: "2BHK Airbnb",
        completion_Data: "2024",
        project_location: "Jaipur, Rajasthan",
        project_type: "Renovation",
        project_desc: [
            "A heritage-inspired Airbnb blending Jaipur’s culture with modern living.",
            "Traditional motifs reinterpreted in a sleek, contemporary style.",
            "Durable materials ensure longevity for frequent guest use.",
            "Executed with detailed supervision and on-time project delivery.",
        ],
        HeroImg: "/Images/projects/airbnb/heroImg.webp",
        images: [
            { type: "landscape", img: "/Images/projects/airbnb/img_8.webp" },
            { type: "portrait", img: "/Images/projects/airbnb/img_1.webp" },
            { type: "portrait", img: "/Images/projects/airbnb/img_2.webp" },
            { type: "landscape", img: "/Images/projects/airbnb/img_4.webp" },
            { type: "landscape", img: "/Images/projects/airbnb/img_5.webp" },
            { type: "portrait", img: "/Images/projects/airbnb/img_3.webp" },
            { type: "portrait", img: "/Images/projects/airbnb/img_7.webp" },
            { type: "landscape", img: "/Images/projects/airbnb/img_6.webp" },
        ],
        tags: [
            "Heritage Modern",
            "Airbnb Design",
            "Durable Finishes",
            "Cultural Aesthetic",
            "Guest Experience",
            "Timely Execution"
        ],
    },
    {
        id: 5,
        title: "3BHK Apartment",
        completion_Data: "2024",
        project_location: "Jaipur, Rajasthan",
        project_type: "Renovation",
        project_desc: [
            "A contemporary home layered with heritage-inspired details.",
            "Gallery wall showcases family legacy through curated art pieces.",
            "Muted palette and balanced layouts maintain openness and calm.",
            "Seamless vendor coordination ensured flawless project execution.",
        ],
        HeroImg: "/Images/projects/apartment/heroImg.webp",
        images: [
            { type: "landscape", img: "/Images/projects/apartment/img_4.webp" },
            { type: "portrait", img: "/Images/projects/apartment/img_2.webp" },
            { type: "portrait", img: "/Images/projects/apartment/img_1.webp" },
            { type: "landscape", img: "/Images/projects/apartment/img_5.webp" },
        ],
        tags: [
            "Modern Heritage",
            "Gallery Wall",
            "Curated Interiors",
            "Balanced Layouts",
            "Cultural Identity",
            "Refined Aesthetic"
        ],
    },
    {
        id: 6,
        title: "Gemstone Application Renders",
        completion_Data: "2022",
        project_location: "Jaipur, Rajasthan",
        project_type: "3D Visualisation",
        project_desc: [
            "Conceptual renders showcasing gemstone panels in diverse interiors.",
            "Focused on balancing luxury materials with functional design.",
            "Checklists ensured stones remained the hero of each render.",
            "Streamlined feedback led to efficient, high-quality visual delivery.",
        ],
        HeroImg: "/Images/projects/gemstone/heroImg.webp",
        images: [
            { type: "landscape", img: "/Images/projects/gemstone/img_1.webp" },
            { type: "portrait", img: "/Images/projects/gemstone/img_4.webp" },
            { type: "portrait", img: "/Images/projects/gemstone/img_6.webp" },
            { type: "portrait", img: "/Images/projects/gemstone/img_7.webp" },
            { type: "portrait", img: "/Images/projects/gemstone/img_2.webp" },
            { type: "portrait", img: "/Images/projects/gemstone/img_3.webp" },
            { type: "portrait", img: "/Images/projects/gemstone/img_5.webp" },
            { type: "portrait", img: "/Images/projects/gemstone/img_9.webp" },
            { type: "portrait", img: "/Images/projects/gemstone/img_10.webp" },
        ],
        tags: [
            "3D Renders",
            "Luxury Materials",
            "Gemstone Design",
            "Visual Storytelling",
            "Functional Aesthetics",
            "Client Collaboration"
        ],
    },
    {
        id: 7,
        title: "Illustrations",
        completion_Data: "2022–2025",
        project_location: "Jaipur",
        project_type: "Illustrations",
        project_desc: [
            "Hand-drawn visuals bringing warmth and individuality to design.",
            "Detailed sketches translate complex spaces into accessible drawings.",
            "Layered checklists ensured accuracy across all illustrations.",
            "Became a signature element of Studio Akto’s bespoke design process.",
        ],
        HeroImg: "/Images/projects/illustrations/heroImg.webp",
        images: [
            { type: "portrait", img: "/Images/projects/illustrations/img_4.webp" },
            { type: "portrait", img: "/Images/projects/illustrations/img_6.webp" },
            { type: "landscape", img: "/Images/projects/illustrations/img_1.webp" },
            { type: "portrait", img: "/Images/projects/illustrations/img_7.webp" },
            { type: "portrait", img: "/Images/projects/illustrations/img_3.webp" },
            { type: "landscape", img: "/Images/projects/illustrations/img_2.webp" },
            { type: "portrait", img: "/Images/projects/illustrations/img_5.webp" },
            { type: "portrait", img: "/Images/projects/illustrations/img_8.webp" },
        ],
        tags: [
            "Hand-Drawn Art",
            "Design Communication",
            "Detailed Sketches",
            "Warm Aesthetic",
            "Creative Process",
            "Artistic Visualization"
        ],
    },
    {
        id: 8,
        title: "Kochi Kochu Office",
        completion_Data: "2025",
        project_location: "Jaipur, Rajasthan",
        project_type: "Renovation",
        project_desc: [
            "A compact workspace designed to feel open, functional, and thoughtfully curated.",
            "Clean lines and a restrained material palette create a balance of warmth and simplicity.",
            "Subtle textures and soft tones add depth without overwhelming the space.",
            "Custom-designed elements enhance usability while giving the office a distinct identity.",
            "Efficient layouts ensure smooth movement and optimal use of every corner.",
            "A calm and cohesive environment that supports focus, interaction, and everyday work."
        ],
        HeroImg: "/Images/projects/kochi_kochu/heroImg.webp",
        images: [
            { type: "portrait", img: "/Images/projects/kochi_kochu/img_1.webp" },
            { type: "portrait", img: "/Images/projects/kochi_kochu/img_2.webp" },
            { type: "landscape", img: "/Images/projects/kochi_kochu/img_3.webp" },
            { type: "landscape", img: "/Images/projects/kochi_kochu/img_4.webp" },
            { type: "portrait", img: "/Images/projects/kochi_kochu/img_5.webp" },
            { type: "portrait", img: "/Images/projects/kochi_kochu/img_11.webp" },
            { type: "landscape", img: "/Images/projects/kochi_kochu/img_6.webp" },
            { type: "portrait", img: "/Images/projects/kochi_kochu/img_7.webp" },
            { type: "portrait", img: "/Images/projects/kochi_kochu/img_8.webp" },
            { type: "landscape", img: "/Images/projects/kochi_kochu/img_9.webp" },
            { type: "landscape", img: "/Images/projects/kochi_kochu/img_10.webp" },
            { type: "landscape", img: "/Images/projects/kochi_kochu/img_12.webp" },
            { type: "portrait", img: "/Images/projects/kochi_kochu/img_13.webp" },
            { type: "portrait", img: "/Images/projects/kochi_kochu/img_14.webp" },
            { type: "landscape", img: "/Images/projects/kochi_kochu/img_15.webp" },
            { type: "portrait", img: "/Images/projects/kochi_kochu/img_16.webp" },
            { type: "portrait", img: "/Images/projects/kochi_kochu/img_17.webp" },
            { type: "landscape", img: "/Images/projects/kochi_kochu/img_18.webp" },
            { type: "portrait", img: "/Images/projects/kochi_kochu/img_19.webp" },
            { type: "portrait", img: "/Images/projects/kochi_kochu/img_20.webp" },
        ],
        tags: [
            "Workspace Design",
            "Minimal Interior",
            "Compact Spaces",
            "Functional Layout",
            "Custom Design",
            "Modern Aesthetic",
            "Spatial Efficiency",
            "Calm Environment"
        ]
    },
    {
        id: 9,
        title: "Rohit Polymers Office",
        completion_Data: "2023",
        project_location: "Jaipur, Rajasthan",
        project_type: "New Build",
        project_desc: [
            "Compact office designed to maximize function and visual openness.",
            "Smart layouts and integrated storage enhance efficiency.",
            "Neutral palette adds sophistication within limited space.",
            "Planned meticulously through checklists and precise coordination.",
        ],
        HeroImg: "/Images/projects/polymer/heroImg.webp",
        images: [
            { type: "portrait", img: "/Images/projects/polymer/img_4.webp" },
            { type: "portrait", img: "/Images/projects/polymer/img_2.webp" },
            { type: "landscape", img: "/Images/projects/polymer/img_6.webp" },
            { type: "portrait", img: "/Images/projects/polymer/img_3.webp" },
            { type: "portrait", img: "/Images/projects/polymer/img_5.webp" },
        ],
        tags: [
            "Compact Office",
            "Smart Planning",
            "Integrated Design",
            "Space Optimization",
            "Modern Workspace",
            "Efficient Execution"
        ],
    },
    {
        id: 11,
        title: "Pottery Studio",
        completion_Data: "2026",
        project_location: "Delhi NCR",
        project_type: "New Build",
        project_desc: [
            "A tactile studio space designed to celebrate the raw, hands-on nature of pottery.",
            "An earthy, muted palette combined with natural textures creates a grounded and immersive environment.",
            "Open yet intuitive layouts allow seamless movement between shaping, drying, and display zones.",
            "Movable shelving systems introduce flexibility, adapting the space to evolving creative needs.",
            "A built-in materials library within the mirror frame transforms functionality into an inspiring display.",
        ],
        HeroImg: "/Images/projects/pottery_studio/heroImg.webp",
        images: [
            { type: "portrait", img: "/Images/projects/pottery_studio/img_1.webp" },
            { type: "portrait", img: "/Images/projects/pottery_studio/img_2.webp" },
            { type: "landscape", img: "/Images/projects/pottery_studio/img_3.webp" },
            { type: "portrait", img: "/Images/projects/pottery_studio/img_4.webp" },
            { type: "portrait", img: "/Images/projects/pottery_studio/img_5.webp" },
            { type: "portrait", img: "/Images/projects/pottery_studio/img_6.webp" },
            { type: "portrait", img: "/Images/projects/pottery_studio/img_7.webp" },
        ],
        tags: [
            "Pottery Studio",
            "Tactile Design",
            "Earthy Aesthetic",
            "Flexible Spaces",
            "Material Exploration",
            "Creative Workspace",
            "Adaptive Design",
            "Craft Environment"
        ],
    },
    {
        id: 10,
        title: "Contemporary Airbnb Rental",
        completion_Data: "2025",
        project_location: "Jaipur, Rajasthan",
        project_type: "New Build",
        project_desc: [
            "A warm, nature-inspired Airbnb blending modern comfort with calm.",
            "Natural materials like wood and cane add organic character.",
            "Layouts optimized for guest comfort and aesthetic balance.",
            "Delivered through clear moodboards and structured coordination.",
        ],
        HeroImg: "/Images/projects/rental/heroImg.webp",
        images: [
            { type: "portrait", img: "/Images/projects/rental/img_1.webp" },
            { type: "portrait", img: "/Images/projects/rental/img_2.webp" },
            { type: "landscape", img: "/Images/projects/rental/img_3.webp" },
        ],
        tags: [
            "Natural Interiors",
            "Airbnb Design",
            "Warm Minimalism",
            "Guest Comfort",
            "Organic Materials",
            "Contemporary Living"
        ],
    },
    {
        id: 12,
        title: "Safeda Farms",
        completion_Data: "2026",
        project_location: "Jaipur, Rajasthan",
        project_type: "Renovation and Inteiror Stying",
        project_desc: [
            "Safeda Farms is a contemporary farmhouse designed around a slower, more connected way of living.",
            "The design brings together earthy materials, warm textures and clean architectural lines to create spaces that feel refined yet rooted in their surroundings.",
            "With an emphasis on natural light, openness and seamless indoor-outdoor transitions, the home balances the character of a countryside retreat with the comfort of a modern residence.",
        ],
        HeroImg: "/Images/projects/safeda_farms/heroImg.webp",
        images: [
            { type: "portrait", img: "/Images/projects/safeda_farms/img_13.webp" },
            { type: "portrait", img: "/Images/projects/safeda_farms/img_9.webp" },
            { type: "landscape", img: "/Images/projects/safeda_farms/img_1.webp" },
            { type: "landscape", img: "/Images/projects/safeda_farms/img_2.webp" },
            { type: "landscape", img: "/Images/projects/safeda_farms/img_3.webp" },
            { type: "landscape", img: "/Images/projects/safeda_farms/img_4.webp" },
            { type: "landscape", img: "/Images/projects/safeda_farms/img_5.webp" },
            { type: "landscape", img: "/Images/projects/safeda_farms/img_6.webp" },
            { type: "landscape", img: "/Images/projects/safeda_farms/img_7.webp" },
            { type: "landscape", img: "/Images/projects/safeda_farms/img_8.webp" },
            { type: "landscape", img: "/Images/projects/safeda_farms/img_10.webp" },
            { type: "landscape", img: "/Images/projects/safeda_farms/img_12.webp" },
            { type: "landscape", img: "/Images/projects/safeda_farms/img_14.webp" },
            { type: "landscape", img: "/Images/projects/safeda_farms/img_15.webp" },
        ],
        tags: [
            "Contemporary Farmhouse",
            "Earthy Materials",
            "Indoor-Outdoor Living",
            "Warm Textures",
            "Connected Living",
        ],
    },
];
